---
name: Molecule Collection Role Test
description: Runs automated tests of an Ansible role inside a collection using Molecule and Podman

inputs:
  role:
    description: Name of role to test
    required: true
  scenario:
    description: Molecule scenario to run
    default: default

runs:
  using: composite
  steps:
    - name: Install podman
      shell: bash
      run: |
        set -ex
        . /etc/os-release
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -y install podman

    - name: Install dependencies
      shell: bash
      run: |
        set -ex
        python -m pip install --upgrade pip
        pip install \
          ansible \
          molecule[podman]==3.4 \
          yamllint \
          pytest-testinfra

    - name: Install the collection
      shell: bash
      run: ansible-galaxy collection install "git+file://$PWD"

    - name: Run tests
      shell: bash
      run: |
        set -ex
        molecule --version
        ansible --version
        cd "roles/${{ inputs.role }}"
        molecule test --scenario-name "${{ inputs.scenario }}"
