---
name: Container Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push container images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - archlinux
          - ubuntu

    steps:
      - uses: actions/checkout@v2

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ansible-molecule-testing
          tags: "${{ matrix.image }}"
          containerfiles: "./Containerfile.${{ matrix.image }}"
          oci: true

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/dannixon
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
